<a href="https://colab.research.google.com/github/YusufAbdurraahman/learning-numpy/blob/main/learning_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

In [9]:
# array 1d
arr = np.array([1,2,3,4,5])
print(arr)

perkalian = arr * 2
print(perkalian)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [10]:
# array 2d
arr2 = np.array([[1,2,3,4],[1,2,3,4]])
print(arr2)

[[1 2 3 4]
 [1 2 3 4]]


In [11]:
# vektor
vek = np.array([[1],[2],[3]])
print(vek)

met = np.array([[1,2,3],[1,2,3]])


print(met)
# tes = vek + met
# print(tes)

[[1]
 [2]
 [3]]
[[1 2 3]
 [1 2 3]]


In [12]:
# matrix

met1 = np.matrix([[1,2,4],[2,1,3]])
met2 = np.matrix([[1],[2],[3]])

ar1 = np.array([[1,2,4],[2,1,3]])
ar2 = np.array([1,2,3])

print(met1)
print(met2)
print(ar1)
print(ar2)

perkalian = met1 * met2
print(perkalian)

perkalian_array = ar1.dot(ar2)
print(perkalian_array)

[[1 2 4]
 [2 1 3]]
[[1]
 [2]
 [3]]
[[1 2 4]
 [2 1 3]]
[1 2 3]
[[17]
 [13]]
[17 13]


In [13]:
import numpy as np

# 1D Array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D:", arr1)
print("Shape:", arr1.shape)

# 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D:\n", arr2)
print("Shape:", arr2.shape)

# 3D Array
arr3 = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
print("\n3D:\n", arr3)
print("Shape:", arr3.shape)


1D: [1 2 3 4 5]
Shape: (5,)

2D:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)


In [14]:
s = np.array([["a","b","c","d"],
              ["e","f","g","h"]])

print(s)
print(s[0][1])

[['a' 'b' 'c' 'd']
 ['e' 'f' 'g' 'h']]
b
