<a href="https://colab.research.google.com/github/YusufAbdurraahman/learning-numpy/blob/main/learning_numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [8,9,10]])

# mengakses baris ke 0 dan sebelum ke 4 dan longkap 2
print(array[0:4:2])

# ambil satu kolom tertentu dari beberapa baris
print(array[1:,2])
print(array[:2])

# ambil satu baris utuh
print(array[1:2])

# ambil satu angka
print(array[0][1])

[[1 2 3]
 [7 8 9]]
[ 6  9 10]
[[1 2 3]
 [4 5 6]]
[[4 5 6]]
2


In [3]:
arr1 = np.array([[1,2,3,4],[1,2,3,4]])
arr2 = np.array([1,2,3,4])

kali = arr1 @ arr2
print(kali)

[30 30]
